# json files location
train_json_dir: datasets/PhoNERT/word/phonert_train.json
val_json_dir: datasets/PhoNERT/word/phonert_val.json
test_json_dir: datasets/PhoNERT/word/phonert_test.json

# model configuration
pretrained_language_model_name: phobert-base
embedding_dim: 300
d_model: 512
pretrained_language_model_dim: 768
dropout: 0.1

# dataset configuration
batch_size: 32
workers: 2

# training configuration
checkpoint: saved_models
root_address: '127.0.0.1'
root_port: '8080'
nodes: 1
process_per_node: 1
rank: 0
learning_rate: 0.01
label_smoothing: 0.1